# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class Investigator(object):
    DETECTIVE = 0
    DOCTOR = 1
    DRIVER = 2
    HUNTER = 3
    MAGICIAN = 4
    OCCULTIST = 5
    REPORTER = 6
